F-MTD Sales = 
CALCULATE(
    [Total Sales],
    TOPN(1, 'Calendar', 'Calendar'[UCT Fiscal Month], DESC))

Diff  % = 
DIVIDE(
    [Current Month] - [Previous Month],
    [Current Month])

Current Month = 
CALCULATE(
    [value],
    TOPN(1, 'Calendar', 'Calendar'[UCT Fiscal Month], DESC))

Previous Month = 
CALCULATE(
    [value],
    FILTER(
        'Calendar',
        'Calendar'[UCT-FiscalMonth#] = MAX('Calendar'[UCT-FiscalMonth#]) - 1))

Inventory Snapshot Value = 
SUMX(
    VALUES('INVENTORY_MSTR'[PART_LOC]),  
    ([Inventory Quantity OH] - [Inventory Quantity Change]) * SUMX(RELATEDTABLE('INVENTORY_COST'), 'INVENTORY_COST'[COST]))

Inventory Value = 
ROUND(
    SUMX(
        INVENTORY_MSTR,
        RELATED(INVENTORY_COST[COST]) * INVENTORY_MSTR[QTY_ONHAND]
    ),
    2)

RevByState = 
SUMX(
    VALUES('ORDER_HIST_LINE'[STATE_SHIP]),
    CALCULATE(SUM('ORDER_HIST_LINE'[EXTENSION])))

