= Table.AddColumn(#"Filtered Rows", "BUCKET", 
each if Text.Contains(Text.Lower([DESCRIPTION]), "upward") then "UPWARD"
    else if Text.Contains(Text.Lower([DESCRIPTION]), "gss") then "GSS" 
    else if Text.Contains(Text.Lower([DESCRIPTION]), "adobe") then "ADOBE" 
    else if Text.Contains(Text.Lower([DESCRIPTION]), "autodesk") then "AUTODESK" 
    else if Text.Contains(Text.Lower([DESCRIPTION]), "ems barcode") then "GSS" 
    else if Text.Contains(Text.Lower([DESCRIPTION]), "go engineer") then "GO ENGINEER" 
    else if Text.Contains(Text.Lower([DESCRIPTION]), "goengineer") then "GO ENGINEER" 
    else if Text.Contains(Text.Lower([DESCRIPTION]), "lenovo") then "LENOVO" 
    else if Text.Contains(Text.Lower([DESCRIPTION]), "it supplies") then "IT" 
    else if Text.Contains(Text.Lower([DESCRIPTION]), "lenovo") then "LENOVO" 
    else if Text.Contains(Text.Lower([DESCRIPTION]), "solarwinds") then "SOLARWINDS" 
    else if Text.Contains(Text.Lower([DESCRIPTION]), "solar winds") then "SOLARWINDS" 
    else if Text.Contains(Text.Lower([DESCRIPTION]), "tulip") then "TULIP" 
    else if Text.Contains(Text.Lower([DESCRIPTION]), "global shop") then "GSS" 
    else if [DESCRIPTION] = "GLOBAL SHOP SOLUTIONS         " then "GSS"
    else null)

    UCT-FiscalQuarter = 
Calendar[UCT-FiscalYear] & "-Q" & 
    SWITCH(
        TRUE(),
        //2022
        INT(([Date] - DATE(2022,01,01))/91) + 1 = 1, "1",
        INT(([Date] - DATE(2022,01,01))/91) + 1 = 2, "2",
        INT(([Date] - DATE(2022,01,01))/91) + 1 = 3, "3",
        INT(([Date] - DATE(2022,01,01))/91) + 1 = 4, "4",
        //2023
        INT(([Date] - DATE(2022,01,01))/91) + 1 = 5, "1",
        INT(([Date] - DATE(2022,01,01))/91) + 1 = 6, "2",
        INT(([Date] - DATE(2022,01,01))/91) + 1 = 7, "3",
        INT(([Date] - DATE(2022,01,01))/91) + 1 = 8, "4",
        //2024
        INT(([Date] - DATE(2022,01,01))/91) + 1 = 9, "1",
        INT(([Date] - DATE(2022,01,01))/91) + 1 = 10, "2",
        INT(([Date] - DATE(2022,01,01))/91) + 1 = 11, "3",
        INT(([Date] - DATE(2022,01,01))/91) + 1 = 12, "4",
        //2025
        INT(([Date] - DATE(2022,01,01))/91) + 1 = 13, "1",
        INT(([Date] - DATE(2022,01,01))/91) + 1 = 14, "2",
        INT(([Date] - DATE(2022,01,01))/91) + 1 = 15, "3",
        INT(([Date] - DATE(2022,01,01))/91) + 1 = 16, "4",
        //2026 - 53 Week Year
        INT(([Date] - DATE(2022,01,01))/91) + 1 = 17, "1",
        INT(([Date] - DATE(2022,01,01))/91) + 1 = 18, "2",
        INT(([Date] - DATE(2022,01,01))/91) + 1 = 19, "3",
        INT(([Date] - DATE(2022,01,01))/98) + 1 = 20, "4",        
        BLANK()
    )