-- Fix AR Customers Open > Over Ships
UPDATE CUST_FORM_INFO 
SET NO_OVER_SHP_QTY = '1'
WHERE REC = '6'

-- Fix Date_Due from incorrect 01/01/1900 date
UPDATE ORDER_HIST_LINE
SET DATE_DUE = DATE_SHIPPED
WHERE ORDER_NO = '0638501' OR ORDER_NO = '0639033'

-- Correct missing INV_History and PO_History (for part Swap to 01)
SELECT * FROM GSS_SWAP_REF
WHERE file_name IN ('LHIST@@@','PHIST@@@') AND TYPE = 'I'

-- Change all reorder qty to 0
UPDATE INVENTORY_MSTR
SET QTY_REORDER = '0' 
WHERE LOCATION = '02'

-- Delete all parts from LOC 02 (after removing from master table, FIXPART8/NF from 1Shot to do the subsequent)
DELETE FROM INVENTORY_MSTR
WHERE LOCATION = '02'
	
DELETE FROM INVENTORY_MST2
WHERE LOCATION = '02'
	
DELETE FROM INVENTORY_MST3
WHERE LOCATION = '02'
	
SELECT * FROM INVENTORY_COST
WHERE LOCN = '02'
	
DELETE FROM INVENTORY_COST
WHERE LOCN = '02'
	
-- To clear up Manufacture to job/stock in locations other than 01
--(Tristan's) Delete "INVENTORY_MSTR" where source_code = 'F' and loc <> '01'
	
DELETE FROM INVENTORY_MSTR
WHERE SOURCE_CODE = 'M' AND LOC <> '01'
	
DELETE FROM INVENTORY_MSTR
WHERE SOURCE_CODE = 'F' AND LOC <> '01'
	
-- Find all parts with either ELBOW or TEE and TANGENT in description
SELECT *
FROM "INVENTORY_MSTR"
WHERE (DESCRIPTION LIKE '%ELBOW%' OR DESCRIPTION LIKE '%TEE%')
AND DESCRIPTION LIKE '%TANGENT%'

-- SORT BY PART ASCENDING
select * from "INVENTORY_MSTR"
WHERE PART LIKE '%3P%'
ORDER BY PART ASC

-- FIND ANY JOB_OP NOT FORMATTED AS DATE
SELECT * FROM JOB_OPERATIONS
WHERE DATE_DUE NOT LIKE '%[0-9]%'

-- WORKING TO FIX THE BAD ENTRIES IN DATE_DUE
select JOB, SUFFIX, SEQ, LMO, PART, UNITS_OPEN, UNITS_COMPLETE, FLAG_CLOSED, DATE_START, DATE_DUE, DATE_COMPLETED from "JOB_OPERATIONS"
WHERE LMO = 'L' AND JOB = '916810'
ORDER BY SUFFIX ASC

-- UPDATE ALL INDIRECT TO WO_DUE = WO_COMPLETED
select JOB, SUFFIX, SEQ, LMO, PART, UNITS_OPEN, UNITS_COMPLETE, FLAG_CLOSED, DATE_START, DATE_DUE, DATE_COMPLETED from "JOB_OPERATIONS"
WHERE LMO = 'L' AND DATE_COMPLETED <> '000000' AND SUFFIX = '23' AND JOB LIKE '%IN%' 

-- UPDATE COUNTRY AND STATE FOR UCT REPORTING
select ORDER_NO, ORDER_LINE, NAME_CUST_SHIP, ADDRESS1_SHIP, ADDRESS2_SHIP, ADDRESS3_SHIP, ADDRESS4_SHIP, ADDRESS5_SHIP, COUNTRY_SHIP from "ORDER_HIST_HEAD"

select ORDER_NO, ORDER_LINE, NAME_CUST_SHIP, ADDRESS1_SHIP, ADDRESS2_SHIP, ADDRESS3_SHIP, ADDRESS4_SHIP, ADDRESS5_SHIP, COUNTRY_SHIP from "ORDER_HIST_LINE"

UPDATE "ORDER_HIST_LINE"
SET STATE_SHIP = 'OR'
WHERE CUSTOMER = '82769'

select * from "CUSTOMER_MASTER"
WHERE (REC = '1' OR REC = '3') 
--AND COUNTRY = ''
--WHERE CUSTOMER = 'W23715'
ORDER BY CUSTOMER ASC

UPDATE "CUSTOMER_MASTER"
SET COUNTRY = 'USA'
WHERE STATE = 'WI'

-- UPDATE ALL 50 STATES USA
UPDATE "CUSTOMER_SHIPTO"
SET COUNTRY_SHIP = 'USA'
WHERE REC = '3'
AND (STATE_SHIP = 'AL' OR STATE_SHIP = 'AK' OR STATE_SHIP = 'AZ' OR STATE_SHIP = 'AR' OR STATE_SHIP = 'CA' OR STATE_SHIP = 'CO' OR STATE_SHIP = 'CT' OR STATE_SHIP = 'DE' OR STATE_SHIP = 'FL' OR STATE_SHIP = 'GA' OR STATE_SHIP = 'HI' OR STATE_SHIP = 'ID' OR STATE_SHIP = 'IL' OR STATE_SHIP = 'IN' OR STATE_SHIP = 'IA' OR STATE_SHIP = 'KS' OR STATE_SHIP = 'KY' OR STATE_SHIP = 'LA' OR STATE_SHIP = 'ME' OR STATE_SHIP = 'MD' OR STATE_SHIP = 'MA' OR STATE_SHIP = 'MI' OR STATE_SHIP = 'MN' OR STATE_SHIP = 'MS' OR STATE_SHIP = 'MO' OR STATE_SHIP = 'MT' OR STATE_SHIP = 'NE' OR STATE_SHIP = 'NV' OR STATE_SHIP = 'NH' OR STATE_SHIP = 'NJ' OR STATE_SHIP = 'NM' OR STATE_SHIP = 'NY' OR STATE_SHIP = 'NC' OR STATE_SHIP = 'ND' OR STATE_SHIP = 'OH' OR STATE_SHIP = 'OK' OR STATE_SHIP = 'OR' OR STATE_SHIP = 'PA' OR STATE_SHIP = 'RI' OR STATE_SHIP = 'SC' OR STATE_SHIP = 'SD' OR STATE_SHIP = 'TN' OR STATE_SHIP = 'TX' OR STATE_SHIP = 'UT' OR STATE_SHIP = 'VT' OR STATE_SHIP = 'VA' OR STATE_SHIP = 'WA' OR STATE_SHIP = 'WV' OR STATE_SHIP = 'WI' OR STATE_SHIP = 'WY');

SELECT * FROM "CUSTOMER_MASTER"
WHERE COUNTRY = '' 
AND (REC = '1' OR REC = '3')
--ORDER BY REC ASC

SELECT * FROM "CUSTOMER_SHIPTO"
WHERE REC = '3' 
--AND COUNTRY_SHIP = '' 
--WHERE STATE_SHIP = 'AL'  AND REC = '3'
ORDER BY STATE_SHIP ASC

-- FILTER BY DATE
SELECT *
FROM "ORDER_HIST_HEAD"
WHERE DATE_SHIPPED > CAST('2023-01-01' AS DATE)

-- 