 #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each let
        // Extract the first 4 characters of the GL_NUMBER to identify the prefixes
        prefix = Text.Start([GL_NUMBER], 4),
        // Extract the last 2 characters to check for "01"
        suffix = Text.End([GL_NUMBER], 2),
        // Check if the GL_NUMBER falls within the specified ranges or equals 1410 or 1440
        withinRanges = 
            List.Contains(
                {
                    "1218-01        ", 
                    "1218-02        ", 
                    "1218-09        ", 
                    "1208-01        ", 
                    "1208-02        ", 
                    "1208-09        ", 
                    "1209-01        ", 
                    "1209-02        ", 
                    "1209-09        ", 
                    "1210-01        ", 
                    "1210-02        ", 
                    "1210-09        ", 
                    "1225-002-01    ", 
                    "1226-01        ", 
                    "1226-09        ", 
                    "1250-01        ", 
                    "1250-02        ", 
                    "1250-09        ", 
                    "1280-01        ", 
                    "1280-02        ", 
                    "1280-09        ", 
                    "1295-01        ", 
                    "1295-02        ", 
                    "1295-09        ", 
                    "1296-01        ", 
                    "1296-02        ", 
                    "1296-09        ", 
                    "1298-01        ", 
                    "1298-02        ", 
                    "1298-09        ", 
                    "1211-01        ", 
                    "1211-02        ", 
                    "1211-09        ", 
                    "1215-01        ", 
                    "1215-02        ", 
                    "1215-09        ", 
                }, 
                [GL_NUMBER]
            )
    in
        withinRanges
),