// INVENTORY COST COMES OUT OF INVENTORY_COST, QTY_OH COMES FROM INVENTORY_MSTR

EXT_COST = 
ROUND(
    SUMX(
        INVENTORY_MSTR,
        RELATED(INVENTORY_COST[UNIT_COST]) * INVENTORY_MSTR[QTY_ONHAND]
    ),
    2
)
